import android.content.Context
import androidx.work.Worker
import androidx.work.WorkerParameters

class MyWorker(context: Context, workerParams: WorkerParameters) : Worker(context, workerParams) {
  override fun doWork(): Result {
    return if (createNotification(
        "Background Task",
        "This notification is generated by workManager"
      )
    ) {
      Result.success()
    } else {
      Result.failure()
    }
  }

  private fun createNotification(title: String, description: String): Boolean {
    createNotification(title, description, applicationContext)
    return true
  }
}