import android.content.Context
import androidx.work.Worker
import androidx.work.WorkerParameters

class MyWorker(context: Context, workerParams: WorkerParameters) : Worker(context, workerParams) {
  override fun doWork(): Result {
    if (createNotification("Background Task", "This notification is generated by workManager")) {
      return Result.success()
    } else {
      return Result.failure()
    }
  }

  private fun createNotification(title: String, description: String): Boolean {
    createNotification(title, description, applicationContext)
    return true
  }
}